---
title: "COVID19 contraction and deathes analysis"
format: html
editor: visual
author: Yuntong Wu & Jiaxin Shen
---

```{r}
#| message: false
here::i_am("Group_Project.Rproj")
library(here)
library(vroom)
library(dplyr)
library(tidyr)
library(ggplot2)
theme_set(theme_bw())
```

Github link:<https://github.com/wuyuntong/Group_Project>

Sources links:
Health data:
<https://www.countyhealthrankings.org/explore-health-rankings/rankings-data-documentation>

Covid data:
<https://usafacts.org/visualizations/coronavirus-covid-19-spread-map/>

Social-economic data:
<https://www.ers.usda.gov/data-products/county-level-data-sets/county-level-data-sets-download-data/>

## Data Loading
```{r}
health <- vroom(here("data", "analytic_data2021.csv"))
cases <- vroom(here("data", "covid_confirmed_usafacts.csv"))
deaths <- vroom(here("data", "covid_deaths_usafacts.csv"))
edu <- vroom(here("data", "Education.csv"))
pop <- vroom(here("data", "PopulationEstimates.csv"))
pov <- vroom(here("data", "PovertyEstimates.csv"))
ump <- vroom(here("data", "Unemployment.csv"))
```

## Data cleaning
```{r}
cov_clean <- function(df) {
  df <- df |>
    select(
      countyFIPS, `County Name`, State, StateFIPS,
      `2020-07-31`, `2020-08-31`, `2020-09-30`, `2020-10-31`,
      `2020-11-30`, `2020-12-31`, `2021-01-31`, `2021-02-28`,
      `2021-03-31`, `2021-04-30`, `2021-05-31`, `2021-06-30`
    ) |>
    rename(
      `2020-07` = `2020-07-31`,
      `2020-08` = `2020-08-31`,
      `2020-09` = `2020-09-30`,
      `2020-10` = `2020-10-31`,
      `2020-11` = `2020-11-30`,
      `2020-12` = `2020-12-31`,
      `2021-01` = `2021-01-31`,
      `2021-02` = `2021-02-28`,
      `2021-03` = `2021-03-31`,
      `2021-04` = `2021-04-30`,
      `2021-05` = `2021-05-31`,
      `2021-06` = `2021-06-30`
    )
}
```

```{r}
cases_mon <- cov_clean(cases)
deaths_mon <- cov_clean(deaths)
```

## Graphic representation of target variables
```{r}
cases_mon |>
  group_by(State) |>
  summarise(across(starts_with("2020"), sum), across(starts_with("2021"), sum)) |>
  pivot_longer(cols = starts_with("202"), names_to = "month", values_to = "count") |>
  ggplot(aes(x = month, y = count, group = State, color = State)) + geom_line() +
  labs(title = "Total cases reported across all 50 states from July 2020 to June 2021") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        plot.title = element_text(margin = margin(b = 40)))
```
```{r}
deaths_mon |>
  group_by(State) |>
  summarise(across(starts_with("2020"), sum), across(starts_with("2021"), sum)) |>
  pivot_longer(cols = starts_with("202"), names_to = "month", values_to = "count") |>
  ggplot(aes(x = month, y = count, group = State, color = State)) + geom_line() +
  labs(title = "Total deaths reported across all 50 states from July 2020 to June 2021") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        plot.title = element_text(margin = margin(b = 40)))
```

